FROM python:3.8

# python:
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONFAULTHANDLER=1 
ENV PYTHONUNBUFFERED=1 
ENV PYTHONHASHSEED=random 
# pip:
ENV PIP_NO_CACHE_DIR=off 
ENV PIP_DISABLE_PIP_VERSION_CHECK=on 
ENV PIP_DEFAULT_TIMEOUT=100 
# poetry:
ENV POETRY_VERSION=1.1.5 
ENV POETRY_VIRTUALENVS_CREATE=false 
ENV POETRY_CACHE_DIR='/var/cache/pypoetry'

RUN pip install poetry==$POETRY_VERSION

WORKDIR /www

ADD pyproject.toml .
ADD poetry.lock .

RUN poetry install

ADD . .