version: "3.8"

services:
  web:
    build: .
    command: gunicorn --workers=2 --bind=0.0.0.0:8000 ecommerce.wsgi:application
    # command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/www
    env_file: 
      - dev.env
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - dev.env
    ports:
      - 5432:5432

volumes:
  postgres_data: